### ISSUE TITLE
getting "command 'extension.hoogle' not found" when I try it

### ISSUE THREAD

**Issue by CarstenKoenig** [caneroj1/hoogle-vscode#1] opened 2017-04-19 16:06 UTC
no matter how I call it (command-palette with or without selected text) I always get the error above.

---

the only additional info I can give is this (straight from the console):

    "jcanero.hoogle-vscode": Cannot find module 'Q'

**Comment by caneroj1** [comment] 2017-04-19 17:24
Hmm. That's odd. It's probably just some sort of bundling issue with the extension, I guess.

I have it installed on my machine and it's working okay.

What's your environment like?

I can take a detailed look at this after 6pm today.

**Comment by vavans** [comment] 2017-04-19 19:39
Hi, i have the same issue. When i'm going into the extension folder, there is a node_modules/q folder. I don't get why it can't retrieve the q module.
Note: i have the issue on linux. On windows, it's working as expected.

**Comment by caneroj1** [comment] 2017-04-20 00:19
@vavans, @CarstenKoenig 

Hey guys,
Can you try installing the extension from this .vsix file? You might need to uninstall the extension first.

If this solves the issue, I'll put out an update so you can just download it that way.

[hoogle-vscode-0.0.1.vsix.zip](https://github.com/caneroj1/hoogle-vscode/files/938940/hoogle-vscode-0.0.1.vsix.zip)

**Comment by caneroj1** [comment] 2017-04-20 12:09
I just released 0.0.2 that should fix your issue.

Try updating to that and let me know if the issue is still happening. Going to close this for now.

**Closed as completed by caneroj1** 2017-04-20 12:09 UTC

**Comment by CarstenKoenig** [comment] 2017-04-20 14:38
yes thank you - this fixed it on both Windows and Linux for me

**Comment by vavans** [comment] 2017-04-20 19:23
It works, thanks !
The infamous case-sensitive difference in file paths between windows and linux ;)
